version: '3.8'
services:
  frontend:
    build: ../frontend
    ports:
      - "4200:80"
    networks:
      - microservice-network

  profile-service:
    build: ../profile-service
    ports:
      - "8080:8080"
    networks:
      - microservice-network

  email-service:
    build: ../email-service
    ports:
      - "8000:8000"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
